import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Section,
  Heading,
  Text,
  Hr,
  Link,
  Row,
  Column,
} from '@react-email/components'
import type { ReportData } from '@/lib/report'

export function ReportEmail({ report, baseUrl }: { report: ReportData; baseUrl: string }) {
  return (
    <Html>
      <Head />
      <Preview>Monthly Inventory Report — {report.month}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>Monthly Inventory Report</Heading>
          <Text style={subtitle}>{report.month}</Text>

          <Section style={summaryCard}>
            <Text style={summaryTitle}>Summary</Text>
            <Row>
              <Column style={statCol}>
                <Text style={statNumber}>{report.summary.totalChanges}</Text>
                <Text style={statLabel}>Stock Changes</Text>
              </Column>
              <Column style={statCol}>
                <Text style={statNumber}>{report.summary.itemsAffected}</Text>
                <Text style={statLabel}>Items Affected</Text>
              </Column>
              <Column style={statCol}>
                <Text
                  style={{
                    ...statNumber,
                    color: report.summary.netChange >= 0 ? '#059669' : '#dc2626',
                  }}
                >
                  {report.summary.netChange >= 0 ? '+' : ''}
                  {report.summary.netChange}
                </Text>
                <Text style={statLabel}>Net Change</Text>
              </Column>
            </Row>
          </Section>

          <Hr style={hr} />

          <Heading as="h2" style={h2}>
            ⚠ Out of Stock ({report.outOfStock.length})
          </Heading>
          {report.outOfStock.length === 0 ? (
            <Text style={emptyText}>No items are currently out of stock.</Text>
          ) : (
            <Section style={listSection}>
              {report.outOfStock.map((item) => (
                <Row key={item.id} style={listRow}>
                  <Column>
                    <Link href={`${baseUrl}/items/${item.slug}`} style={link}>
                      {item.name}
                    </Link>
                  </Column>
                </Row>
              ))}
            </Section>
          )}

          <Hr style={hr} />

          <Heading as="h2" style={h2}>
            📈 Went Out of Stock This Month ({report.wentOutOfStock.length})
          </Heading>
          {report.wentOutOfStock.length === 0 ? (
            <Text style={emptyText}>No items went out of stock this month.</Text>
          ) : (
            <Section style={listSection}>
              {report.wentOutOfStock.map((item) => (
                <Row key={item.id} style={listRow}>
                  <Column>
                    <Link href={`${baseUrl}/items/${item.slug}`} style={link}>
                      {item.name}
                    </Link>
                  </Column>
                  <Column style={{ width: 120, textAlign: 'right' }}>
                    <Text style={dateText}>
                      {new Date(item.date).toLocaleDateString()}
                    </Text>
                  </Column>
                </Row>
              ))}
            </Section>
          )}

          <Hr style={hr} />

          <Heading as="h2" style={h2}>
            🏆 Top Changes This Month
          </Heading>
          {report.topChanges.length === 0 ? (
            <Text style={emptyText}>No stock changes this month.</Text>
          ) : (
            <Section style={tableSection}>
              <Row style={tableHeader}>
                <Column style={thCol}>Item</Column>
                <Column style={thColNarrow}>Change</Column>
                <Column style={thCol}>Reason</Column>
              </Row>
              {report.topChanges.map((item) => (
                <Row key={item.id} style={tableRow}>
                  <Column style={tdCol}>
                    <Link href={`${baseUrl}/items/${item.slug}`} style={link}>
                      {item.name}
                    </Link>
                  </Column>
                  <Column
                    style={{
                      ...tdColNarrow,
                      color: item.change >= 0 ? '#059669' : '#dc2626',
                    }}
                  >
                    {item.change >= 0 ? '+' : ''}
                    {item.change}
                  </Column>
                  <Column style={tdCol}>{item.reason ?? '—'}</Column>
                </Row>
              ))}
            </Section>
          )}

          <Hr style={hr} />

          <Text style={footer}>
            This report was automatically generated by your Inventory Manager.
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

const main = {
  backgroundColor: '#f4f4f5',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif',
  padding: '20px 0',
}

const container = {
  backgroundColor: '#ffffff',
  border: '1px solid #e5e7eb',
  borderRadius: '8px',
  margin: '0 auto',
  maxWidth: '600px',
  padding: '32px',
}

const h1 = {
  fontSize: '24px',
  fontWeight: 700,
  margin: '0 0 4px',
  color: '#111827',
}

const subtitle = {
  fontSize: '14px',
  color: '#6b7280',
  margin: '0 0 24px',
}

const summaryCard = {
  backgroundColor: '#f9fafb',
  borderRadius: '8px',
  padding: '20px',
  marginBottom: '24px',
}

const summaryTitle = {
  fontSize: '14px',
  fontWeight: 600,
  color: '#374151',
  margin: '0 0 16px',
  textTransform: 'uppercase' as const,
  letterSpacing: '0.05em',
}

const statCol = {
  width: '33%',
  textAlign: 'center' as const,
}

const statNumber = {
  fontSize: '28px',
  fontWeight: 700,
  color: '#111827',
  margin: '0',
}

const statLabel = {
  fontSize: '12px',
  color: '#6b7280',
  margin: '4px 0 0',
}

const h2 = {
  fontSize: '16px',
  fontWeight: 600,
  color: '#111827',
  margin: '0 0 12px',
}

const emptyText = {
  fontSize: '14px',
  color: '#9ca3af',
  margin: '0 0 24px',
}

const listSection = {
  marginBottom: '24px',
}

const listRow = {
  padding: '8px 0',
  borderBottom: '1px solid #f3f4f6',
}

const link = {
  color: '#4f46e5',
  textDecoration: 'none',
  fontSize: '14px',
}

const dateText = {
  fontSize: '13px',
  color: '#9ca3af',
  margin: '0',
}

const tableSection = {
  marginBottom: '24px',
}

const tableHeader = {
  borderBottom: '2px solid #e5e7eb',
  paddingBottom: '8px',
  marginBottom: '4px',
}

const thCol = {
  fontSize: '12px',
  fontWeight: 600,
  color: '#6b7280',
  textTransform: 'uppercase' as const,
  padding: '4px 8px',
}

const thColNarrow = {
  width: '80px',
  fontSize: '12px',
  fontWeight: 600,
  color: '#6b7280',
  textTransform: 'uppercase' as const,
  padding: '4px 8px',
  textAlign: 'right' as const,
}

const tableRow = {
  borderBottom: '1px solid #f3f4f6',
}

const tdCol = {
  fontSize: '14px',
  padding: '8px',
}

const tdColNarrow = {
  width: '80px',
  fontSize: '14px',
  fontWeight: 600,
  padding: '8px',
  textAlign: 'right' as const,
}

const hr = {
  border: 'none',
  borderTop: '1px solid #e5e7eb',
  margin: '24px 0',
}

const footer = {
  fontSize: '12px',
  color: '#9ca3af',
  textAlign: 'center' as const,
  margin: '0',
}
